version: "2"

services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - ./data/postgresql:/var/lib/mysql
    restart: always
    environment:
      - POSTGRES_USER=wifipunch
    ports:
      - 127.0.0.1:5432:5432

  wifipunch:
    depends_on:
      - db
    build: .
    volumes:
      - "${VOLUME_PATH}wifipunch:/wifipunch"
    restart: always
    environment:
      - FLASK_ENV
      - FROM_EMAIL
      - TO_EMAIL
      - SENDGRID_API_KEY
      - WIFIPUNCH_API_KEY
      - FLASK_APP=/wifipunch/app.py
    network_mode: "host"

volumes:
  wifipunch:

