version: '3.3'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./data/postgresql:/var/lib/mysql
    restart: always
    networks:
      - private

  wifipunch:
    depends_on:
      - db
    build: .
    #context: .
    #dockerfile: Dockerfile
    volumes:
      - ./wifipunch:/wifipunch
    ports:
      - "8000:80"
    restart: always
    # TODO: check if .env environment is passed to the container
    # environment:
    #   - SUBNET="${SUBNET}"
    environment:
      - FLASK_ENV
    networks:
      - private
      - myvlan

networks:
  private:
  # MacVlan so the container can sniff the network
  myvlan:
    driver: macvlan
    driver_opts:
      parent: "${INTERFACE}"
    ipam:
      config:
        - subnet: "${SUBNET}"
