"""empty message

Revision ID: 2dc510fd2b1e
Revises: 3fa50d0721ce
Create Date: 2019-05-21 14:48:09.607887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc510fd2b1e'
down_revision = '3fa50d0721ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'macaddress', ['mac'])
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'macaddress', type_='unique')
    # ### end Alembic commands ###
