"""empty message

Revision ID: 449e461c7b5f
Revises: 7edbf488731c
Create Date: 2019-05-31 19:43:40.078974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449e461c7b5f'
down_revision = '7edbf488731c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
