"""empty message

Revision ID: 7edbf488731c
Revises: b4e7bedaed92
Create Date: 2019-05-21 17:07:18.335916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edbf488731c'
down_revision = 'b4e7bedaed92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelog', sa.Column('user', sa.String(), nullable=True))
    op.drop_column('timelog', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelog', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('timelog', 'user')
    # ### end Alembic commands ###
