"""empty message

Revision ID: b4e7bedaed92
Revises: bceabfde0ee7
Create Date: 2019-05-21 17:06:45.881869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e7bedaed92'
down_revision = 'bceabfde0ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelog', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('timelog', sa.Column('mac_address', sa.String(), nullable=True))
    op.drop_constraint('timelog_mac_addresses_id_fkey', 'timelog', type_='foreignkey')
    op.drop_constraint('timelog_user_id_fkey', 'timelog', type_='foreignkey')
    op.drop_column('timelog', 'mac_addresses_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelog', sa.Column('mac_addresses_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('timelog_user_id_fkey', 'timelog', 'user', ['user_id'], ['id'])
    op.create_foreign_key('timelog_mac_addresses_id_fkey', 'timelog', 'macaddress', ['mac_addresses_id'], ['id'])
    op.drop_column('timelog', 'mac_address')
    op.drop_column('timelog', 'ip')
    # ### end Alembic commands ###
